### PR TITLE
Avoid root owner when linux host; only use patchelf and not chrpath

### PR DESCRIPTION
**Pull request by smitgd**
build-helper.sh changes:
-When build host is linux, run build.sh in docker/debian as a non-root
user having uid and gid matching the non-root linux user. This prevents
docker/debian from creating dirs/files owned by root.
-Removed some unused variables.
-In openocd executable, check for RUNPATH (set by patchelf) instead of RPATH.
-Remove error inhibits (set +e/-e) around patchelf called for libraries. Need
to know if patchelf fails since this can cause openocd to fail at runtime.

build-openocd.sh changes:
-Fix --help usage string for "--helper-script file".
-Remove check for chrpath since it is replaced with patchelf.
-Remove RPATH setting to $ORIGIN in LDFLAGS since patchelf also sets RUNPATH
to $ORIGIN in openocd executable.

### CODE REVIEW

**Comment by smitgd** [comment]
Here are my suggested changes.

**Comment by ilg-ul** [comment]
thank you for the patches, they look ok.

however I would like you to better explain the difference between RPATH & RUNPATH, since I don't know the details; also, when using patchelf, be sure you set the correct one, and explain this in the code.

it is also very important that your scripts generate correct binaries on macOS. did you try this?

**Comment by smitgd** [comment]
Sorry for delay in answering. Should have answers to your questions soon...

**Comment by ilg-ul** [comment]
later this week I plan to make some new releases, so it would be useful to clarify these details and update the pull request so I can apply the patch.

**Comment by smitgd** [comment]
I have re-evaluated my approach and found that there is a much easier way to produce folders with non-root owner than running the script in docker as a different user. Also, I thinks it is better if I split this into two pull requests with one just handling the owner change and another doing the patchelf usage. So I will close this with this comment and submit two separate pull requests.

**Comment by ilg-ul** [comment]
ok, good plan.

**Pull request closed without merging**
